#
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
#

# Core Properties
spring.application.name: spring-web-jpa-concurrency
spring.profiles.active: default
spring.threads.virtual.enabled: true

# Database configuration
spring.datasource:
    url: jdbc:mysql://${MYSQL_SERVER}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.properties.hibernate:
    hibernate.ddl-auto: update
    show_sql: true
    format_sql: true
    use_sql_comments: true
    id.new_generator_mappings: true
    type: trace
    generate_statistics: true

# Docker Compose Properties


