name: Run gradlew test

on:
  pull_request:
    branches:
      - develop
      - feature/**

jobs:
  setup_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '21'
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run gradlew test
        run: ./gradlew test --warning-mode=all

  coverage:
    needs: setup_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Upload test coverage to Codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: spring-templates/spring-concurrency-thread
          fail_ci_if_error: true
          verbose: true
          flags: ${{ github.ref == 'refs/pull/develop' && 'integration' || 'unittests' }}
